import React from 'react'

function Footer() {
  return (
    <div>
      Footer
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
      <h1>sladkjsh</h1>
    </div>
  )
}

export default Footer